**Sentencias de control**

**def, if, else, return**

In [1]:
def resultado(x):
    if x<=10.4:
        salida="desaprobado"
    else:
        salida="aprobado"
    return salida

In [2]:
resultado(x=12)

'aprobado'

**elif**

In [3]:
def resultado2(x):
    if 0<=x<=10.4:
        salida="desaprobado"
    elif 10.4 <x<14:
        salida="aprobado pero sin créditos"
    elif 14<=x<=20:
        salida="aprobado más créditos"
    else:
        salida="fuera de rango"
    return salida

In [4]:
#valores numéricos
#estructura de objetos en python
#objetos numéricos, vectores, matrices, listas, diccionarios, etc.

**for**

**break**

In [5]:
# bucles


for i in range(2,11):
    if i == 4:
        break
    print(i*2)

4
6


In [6]:
range(2,12) #2,3,4,5,6....11

range(2, 12)

In [7]:
#optimización de parámetros en nuestros modelos


**while**

In [8]:
x=2
y=4

In [9]:
x=2
y=4
while x < y:
    print(x*2)
    x +=1
#bucles condicionales

4
6


In [10]:
for i in range(2,10):
    if i % 2!=0:
        continue
    print(i)

2
4
6
8


In [11]:
#caracteristicas
#sentencias
#estructura báscica de objetos
#opereaciones con esta estructura de objetos.

#lista 

**Lista**

In [12]:
lista1 = [4,5,6]

In [13]:
print(lista1)

[4, 5, 6]


In [14]:
type(lista1) #función type nos permite conocer la estructura de objeto con la cual estamos trabajando


list

**Tipeado dinámico**

In [15]:
lista2 = lista1

In [16]:
lista2

[4, 5, 6]

In [17]:
lista1

[4, 5, 6]

In [18]:
lista1[0]=15

In [19]:
lista1 #efectivamente el valor 4 fue reemplazado por 15

[15, 5, 6]

In [20]:
lista2

[15, 5, 6]

In [21]:
lista3 = lista1.copy()

In [22]:
#esta función copy() rompe con el tipeado dinámico y podemos realizar modificaciones

In [23]:
lista1[0]=4

In [24]:
lista1

[4, 5, 6]

In [25]:
lista3

[15, 5, 6]

**Números**

In [26]:
n_entero = 20

In [27]:
n_entero2 = n_entero

In [28]:
print(n_entero)

20


In [29]:
print(n_entero2)

20


In [30]:
n_entero =21

In [31]:
n_entero2

20

In [32]:
#valores dentro de los definidos

In [33]:
type(n_entero)

int

In [34]:
n_real = 20.5

In [35]:
type(n_real)

float

In [36]:
#formatos
#integer: se refieren a valores numéricos enteros
#float: se refieren a valores numéricos reales

In [37]:
n_real2 = 0.000000000000000000015

In [38]:
n_real2

1.5e-20

In [39]:
n_complejo = 4.1 + 7j

In [40]:
n_complejo

(4.1+7j)

In [41]:
#no trabajamos con valores complejos para nuestros modelos

In [54]:
import os
import pandas as pd

In [55]:
os.getcwdb()

b'/home/erik/Documentos/cursos/Data-Science/codigo'

In [56]:
os.chdir("/home/erik/Documentos/cursos/Data-Science/Data")
#os.chdir(): es la función para definir tu directerio de trabajo

In [57]:
os.getcwd()
#os.getcwd():función para consulta el directorio de trabajo

'/home/erik/Documentos/cursos/Data-Science/codigo'

In [58]:
df=pd.read_csv("LL.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'LL.csv'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722 entries, 0 to 721
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   treated    722 non-null    int64  
 1   age        722 non-null    int64  
 2   education  722 non-null    int64  
 3   black      722 non-null    int64  
 4   married    722 non-null    int64  
 5   nodegree   722 non-null    int64  
 6   re74       722 non-null    float64
 7   re75       722 non-null    float64
 8   re78       722 non-null    float64
 9   hispanic   722 non-null    int64  
 10  u74        722 non-null    int64  
 11  u75        722 non-null    int64  
dtypes: float64(3), int64(9)
memory usage: 67.8 KB


In [ ]:
df.head()

treated  age  education  black  married  nodegree          re74  \
0        1   33         12      0        1         0      0.000000   
1        1   20         12      0        1         0   8644.156250   
2        0   39         12      1        1         0  19785.320312   
3        1   49          8      0        1         1   9714.596680   
4        0   26          8      0        1         1  37211.757812   

           re75          re78  hispanic  u74  u75  
0      0.000000  12418.070312         0    1    1  
1   8644.156250  11656.505859         0    0    0  
2   6608.137207    499.257202         0    0    0  
3   7285.947754  16717.121094         0    0    0  
4  36941.265625  30247.500000         0    0    0

In [ ]:
etiquetas=df.columns.tolist()

In [ ]:
print(etiquetas)

['treated', 'age', 'education', 'black', 'married', 'nodegree', 're74', 're75', 're78', 'hispanic', 'u74', 'u75']


**Sistemas numéricos**

In [ ]:
n_bin = 0b1111
print(n_bin)

15


In [ ]:
n_oct = 0o10
print(n_oct)

8


In [ ]:
n_hex = 0xf
print(0xf)

15


In [ ]:
#python puedes ingresar los valores numéricos en diferentes sistemas e internamente lo convierte al sistema decimal

In [ ]:
bin(10)

'0b1010'

In [ ]:
oct(10)

'0o12'

In [ ]:
hex(10)

'0xa'

**Conjunto**

In [ ]:
conjuntoa = {1,2,3,4}

In [ ]:
print(conjuntoa)

{1, 2, 3, 4}


In [ ]:
conjunto2 = set("1234")

In [ ]:
print(conjunto2)

{'2', '1', '3', '4'}


In [ ]:
#formato tipo caracter = texto = string

In [ ]:
conjuntob= {2,4,6,8}

In [ ]:
conjuntoa & conjuntob

{2, 4}

In [ ]:
conjuntoa.intersection(conjuntob)

{2, 4}

In [ ]:
#por teoría los conjuntos no guardan valores duplicados

In [ ]:
duplicados = {2,3,4,5,6,7,8,8,8,10}

In [ ]:
print(duplicados)

{2, 3, 4, 5, 6, 7, 8, 10}


In [ ]:
del duplicados
#del para eliminar objetos creados conjuntos, listas, vectores, diccionarios

In [ ]:
duplicados

NameError: name 'duplicados' is not defined

**Cadena de texto**

In [ ]:
texto = "esto es un texto"

In [ ]:
type(texto) #la salida nos muestra que es un objeto tipo string

str

In [ ]:
#encoding 
#código de texto
#nos lo proporciona el DBA





In [ ]:
texto2 = b"esto es un texto de formato byte"

In [ ]:
type(texto2)

bytes

In [ ]:
bytearray("Perú","utf16")

bytearray(b'\xff\xfeP\x00e\x00r\x00\xfa\x00')

In [ ]:
string = "objeto string"

In [ ]:
string.encode()

b'objeto string'

In [ ]:
byte = b"soy un byte"

In [ ]:
print(byte)

b'soy un byte'


In [ ]:
byte.decode()

'soy un byte'

In [ ]:
"https://www.buscalibre.pe/libros/search?q=Big+data&page="

In [ ]:
urls = []
#urls es un objeto tipo lista vacío donde se guardarán los url generados en el bucle haciendo uso de la sentencia
#append
for i in range(1,18):
    url = "https://www.buscalibre.pe/libros/search?q=Big+data&page="+str(i)
    urls.append(url)

In [ ]:
#str(): función para convertir a formato string

In [ ]:
print(urls)

['https://www.buscalibre.pe/libros/search?q=Big+data&page=1', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=2', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=3', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=4', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=5', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=6', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=7', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=8', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=9', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=10', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=11', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=12', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=13', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=14', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=15', 'https://www.buscalibre.pe/libros/search?q=Big+data&page=16', 'https://www.bus

In [ ]:
type(urls)

list

**Operaciones con objetos tipo string**

In [ ]:
curso = "R for Data Science"

In [ ]:
curso = curso.replace("R", "Python")

In [ ]:
print(curso)

Python for Data Science


In [ ]:
len(curso)

23

In [ ]:
curso.upper()

'PYTHON FOR DATA SCIENCE'

In [ ]:
curso.lower()

'python for data science'

In [ ]:
nombre = " Linder "

In [ ]:
nombre

' Linder '

In [ ]:
nombre.lstrip()

'Linder '

In [ ]:
nombre.rstrip()

' Linder'

In [ ]:
nombre.strip()

'Linder'

In [ ]:
curso[0:15]

'Python for Data'

In [ ]:
len(curso)

23

In [ ]:
curso_list=curso.split(" ")

In [ ]:
curso_list

['Python', 'for', 'Data', 'Science']

In [ ]:
curso.find("f")
#find() busca el valor ingresado en el objeto

7

**Listas**

Las listas nos permite almacenar valores de diferentes formatos

In [ ]:
alumno = ["Cesar", "UPC", "True", 30]

In [ ]:
print(alumno)

['Cesar', 'UPC', 'True', 30]


In [ ]:
alumno[1]="PUCP"

In [ ]:
alumno

['Cesar', 'PUCP', 'True', 30]

In [ ]:
alumno.append("Lince")

In [ ]:
alumno

['Cesar', 'PUCP', 'True', 30, 'Lince']

In [ ]:
del alumno

In [ ]:
alumno

NameError: name 'alumno' is not defined

In [ ]:
alumno = ["Cesar", "UPC", "True", 30]

In [ ]:
type(alumno)

list

**¿Existen vectores en python?**

In [ ]:
import numpy as np

**Vectores**

In [ ]:
#sólo admite un formato para el objeto creado

In [ ]:
edades = np.array([25,27,23,28,29,21])

In [ ]:
print(edades)

[25 27 23 28 29 21]


In [ ]:
type(edades)

numpy.ndarray

In [ ]:
edades[0]=26

In [ ]:
print(edades)

[26 27 23 28 29 21]


In [ ]:
#eliminar por posicion

edades2=np.delete(edades,[0,2])
print(edades2)


[27 28 29 21]


**Tuplas**

In [ ]:
#objetos que una vez creados son inmodificables

In [ ]:
alumnotupla = ("Cesar",30,"UPC")

In [ ]:
alumnotupla[1]=28

TypeError: 'tuple' object does not support item assignment

In [ ]:
alumnotupla2 = "Cesar",30,"UPC"

In [ ]:
type(alumnotupla2)

tuple

**Diccionarios**

In [ ]:
#ficheros tipo JSON tienen una estructura muy similar a la de un diccionario de python
#admiten diferentes formatos

In [ ]:
alumnodicc = {"alumno": "Cesar",
             "edad":30,
             "masculino": True,
             "distrito": "Lince"}

In [ ]:
type(alumnodicc)

dict

In [ ]:
alumnodicc["edad"] =28

In [ ]:
print(alumnodicc)

{'alumno': 'Cesar', 'edad': 28, 'masculino': True, 'distrito': 'Lince'}


In [ ]:
edades = [24,25,27,21,25]
nombres = ["Michael", "Oscar","Roger","Romario","Andrea"]

In [ ]:
alumnodicc = {"alumno":nombres,
             "edades":edades}

In [ ]:
alumnodicc

{'alumno': ['Michael', 'Oscar', 'Roger', 'Romario', 'Andrea'],
 'edades': [24, 25, 27, 21, 25]}

**¿Existen dataframe en python?**

In [ ]:
import pandas as pd

In [ ]:
data_alumnos = pd.DataFrame(alumnodicc)

In [ ]:
data_alumnos.head()

alumno  edades
0  Michael      24
1    Oscar      25
2    Roger      27
3  Romario      21
4   Andrea      25